# Generated by Django 6.0 on 2026-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_assistantphrase_product_name_kg_product_name_ru_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_deleted_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
